# Generated by Django 4.1.3 on 2023-04-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="about",
            field=models.TextField(default="about"),
        ),
    ]
